#!/bin/bash

ROOT=$(cd "$(dirname "$0")/.."; pwd)

FILES=$(find $ROOT/src -name '*.test.ts')

if [[ $* == *--browser* ]]; then
  grep -lE "@group\s+browser" $FILES
elif [[ $* == *--node* ]]; then
  grep -lE "@group\s+node" $FILES
fi
